### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by dannyvassallo** [TSMMark/pwnagon#17]
``` css
  body {
    display: flex;
    min-height: 100vh;
    flex-direction: column;
  }

  main {
    flex: 1 0 auto;
  }
```

Could use sticky footer to fix pages like this:  https://pwnagon-qa.herokuapp.com/users/sign_in
